version: '3.8'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 11000:11000
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - ./.env